---
- name: First setup
  hosts: docker_tree
  become: yes
  tasks:
  - name: build docker image
    shell:
      cmd: docker build -t tree https://github.com/presiannedyalkov/xmas-tree.git
  - name: run docker image
    shell:
      # chdir: /home/pi/xmas-tree
      cmd: docker run --rm --cap-add SYS_RAWIO --device /dev/mem --name tree -t tree